
apiVersion: apps/v1
kind: Deployment
metadata:
  name: t41-server-deployment
  labels:
    app: t41-server
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: t41-server
  template:
    metadata:
      labels:
        app: t41-server
    spec:
      imagePullSecrets:
      - name: timeweb-registry-secret

      containers:
      - name: t41-server
        
        image: ...registry.twcstorage.ru/t41-server:latest
        command: ["/usr/local/bin/server", "--mode", "production", "--role", "monolith"]

        imagePullPolicy: Always 

        ports:
        - containerPort: 8080 
        - containerPort: 8081 
        - containerPort: 8082 

        envFrom:
        - configMapRef:
            name: serverpod-config-t41 
        
        env:
        - name: SERVERPOD_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: serverpod-secrets-t41 
              key: database-password 
        - name: SERVERPOD_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: serverpod-secrets-t41
              key: redis-password
        - name: SERVERPOD_SERVICE_SECRET
          valueFrom:
            secretKeyRef:
              name: serverpod-secrets-t41
              key: service-secret

        readinessProbe:
          httpGet:
            path: / 
            port: 8082
          initialDelaySeconds: 20 
          periodSeconds: 15     

        livenessProbe:
          httpGet:
            path: /
            port: 8082
          initialDelaySeconds: 60 
          periodSeconds: 30

    