

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: t41-server-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx" 
    cert-manager.io/cluster-issuer: "letsencrypt-prod" 
spec:
  tls:
  - hosts:
    - api41.my-points.ru
    - web41.my-points.ru
    - insights41.my-points.ru
    secretName: serverpod-tls-t41
  rules:
  - host: "api41.my-points.ru"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: t41-server-service
            port:
              name: api
  - host: "web41.my-points.ru"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: t41-server-service
            port:
              name: web
  - host: "insights41.my-points.ru"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: t41-server-service
            port:
              name: insights
    